### ISSUE TITLE
elementui有关于popper，下拉错位

### ISSUE THREAD

**Issue by gg-guang** [Auto-Plugin/autofit.js#55]

**Comment by LarryZhu-dev** [comment]
据了解，elementUI 等使用的是 [floating-ui](https://github.com/floating-ui/floating-ui) / [popper.js](https://popper.js.org/docs/v2/) 插件 实现的弹出层，但是popper.js在计算弹出元素位置时，没有考虑页面整体缩放偏移的情况，所以在autofit.js的缩放方案中，会出现偏移错位的问题，目前autofit.js有计划使用其他方式解决偏移，但近期还没有好的方案，你可以尝试去[floating-ui](https://github.com/floating-ui/floating-ui)提个issue。

**Comment by zhengdechang** [comment]
哪个ui支持的下拉框和弹框适配这个 @LarryZhu-dev

**Comment by LarryZhu-dev** [comment]
@zhengdechang 目前已知国内主流组件库都不支持autofit.js
但是有一些国外的小众UI库是支持的：
Vuestic UI ：https://github.com/epicmaxco/vuestic-ui
其实没有一些，目前只发现这一个🤡

**Comment by zhengdechang** [comment]
> @zhengdechang 目前已知国内主流组件库都不支持autofit.js 但是有一些国外的小众UI库是支持的： Vuestic UI ：https://github.com/epicmaxco/vuestic-ui 其实没有一些，目前只发现这一个🤡

有没有react的呢

**Comment by LarryZhu-dev** [comment]
@zhengdechang 我这暂时没发现呢

**Comment by zhengdechang** [comment]
antd作为国内比较热门的组件库，能否抽空做一下适配呢，大佬。
现在antd遇到的组件有Popover、dropdown、select下拉

> @zhengdechang 我这暂时没发现呢

**Comment by LarryZhu-dev** [comment]
> antd作为国内比较热门的组件库，能否抽空做一下适配呢，大佬。 现在antd遇到的组件有Popover、dropdown、select下拉
> 
> > @zhengdechang 我这暂时没发现呢

这个我这边解决不了哈，需要antd去做适配呢

**Comment by TopAlien** [comment]
> antd作为国内比较热门的组件库，能否抽空做一下适配呢，大佬。 现在antd遇到的组件有Popover、dropdown、select下拉
> 
> > @zhengdechang我暂时没有发现呢

getPopupContainer 挂载一下

**Comment by guosuwei** [comment]
> > antd作为国内比较热门的组件库，能否抽空做一下适配呢，大佬。 现在antd遇到的组件有Popover、dropdown、select下拉
> > > @zhengdechang我暂时没有发现呢
> 
> getPopupContainer 挂载一下

elementUI 有办法处理吗

**Comment by ezewu** [comment]
目前，有弹出的，就跑错位了，是一个问题

**Comment by gemdeng** [comment]
Naive UI也会出现这个问题

**Comment by wanglei1020** [comment]
> > > antd作为国内比较热门的组件库，能否抽空做一下适配呢，大佬。 现在antd遇到的组件有Popover、dropdown、select下拉
> > > > @zhengdechang我暂时没有发现呢
> > 
> > 
> > getPopupContainer 挂载一下
> 
> elementUI 有办法处理吗

实测element-ui@2.15.14已解决，贴出方案供大家参考：

在`element-ui/lib/utils/popper.js`的第421行下新增代码：
```js
// 修复使用autofit.js导致的popover错位问题
// 这里的body对应的是autofit.init({el: 'body‘})
const targetEl = document.querySelector('body')
const scaleMatch = targetEl.style.getPropertyValue('transform').match(/scale\((.*?)\)/)
// 获取缩放比例
const scale = scaleMatch ? +scaleMatch[1] : 1
Object.keys(referenceOffsets).forEach((key) => {
    referenceOffsets[key] = referenceOffsets[key] / scale
})
```
刷新页面，元素位置已经是正确的了

因为直接改的源码，需要使用`patch-package`包把修改以补丁的形式保存起来，并纳入`git`管理，具体用法自行百度。

其他版本不知道代码位置会不会变，可以自己找找，应该变化不大。贴个图：
![image](https://github.com/user-attachments/assets/ff4a585a-6bf1-4484-b3b0-16f797cbedfc)

**Comment by JunIce** [comment]
楼上老哥的方案实测可用  版本 2.5.13

**Comment by wyman51t** [comment]
感谢诸位大佬element-ui@2.15.14实测可用

**Comment by LarryZhu-dev** [comment]
使用 ignore 传入子串匹配选择器可解决弹出层偏移问题，在 element-plus 中，有一个id为el-popper-container-xxx的元素，将其传入 ignore 即可，对于 element-ui ，需要将弹出元素挂载到 body 根节点，或其他任何不在 autofit 影响下的节点即可，如 element 弹出层挂载到 `body`， autofit 挂载到 `#app`，参考文档：https://auto-plugin.github.io/autofit.js/api.html#element-%E7%AD%89%E5%BC%B9%E5%87%BA%E5%B1%82%E5%81%8F%E7%A7%BB

#67 #77

**Comment by binggana** [comment]
element-ui@2.15.14和element-ui@2.15.15版本都试过上面说的修改node_modules\element-ui\lib\utils\popper.js，没有生效啊(╥╯^╰╥)

**Comment by LarryZhu-dev** [comment]
@binggana element-ui 可以使用我们魔改版的，支持 autofit ，见：https://github.com/Auto-Plugin/auto-element
