### ISSUE TITLE
Vue3 element-plus dialog组件导致页面留白

### ISSUE THREAD

**Issue by easy868** [Auto-Plugin/autofit.js#78]
![image](https://github.com/user-attachments/assets/d8b6ae98-0a0b-4ae9-aa19-6e17fd846d2c)
![image](https://github.com/user-attachments/assets/6f5ddb67-e8f7-44de-8c17-360b1b0d32f2)
初始化配置：

autofit.init({
  dw: 1920,
  dh: 1080,
  ignore: [{ el: '#mapView' }, 'div[id*="el-popper-container"]'] //'div[id*="el-popper-container"]'解决element弹出层偏移
})
dialog弹出后会导致页面重新尺寸，尺寸不对

**Comment by easy868** [comment]
更新到了2.9.0还是不行，浏览器100%缩放时还是会有问题，90%缩放时正常

**Comment by LarryZhu-dev** [comment]
没有复现你的问题，能不能写一个复现案例 https://stackblitz.com/

**Comment by easy868** [comment]
![image](https://github.com/user-attachments/assets/360d1b2d-cb70-4db7-9516-a50a576fc961)
[https://element-plus.org/zh-CN/component/dialog.html#dialog-%E5%AF%B9%E8%AF%9D%E6%A1%86](url)
直接element-plus官网就能复现，我试了下，是因为lock-scroll默认为true，会设置body宽度，设为false就可以了
![image](https://github.com/user-attachments/assets/6c296495-843f-4555-a509-5a5a9c708cea)

**Comment by LarryZhu-dev** [comment]
好的，感谢提供问题，如果还有其他问题，可以继续留言
