### ISSUE TITLE
引入echarts后会导致autofit.js失效

### ISSUE THREAD

**Issue by lhhboy** [Auto-Plugin/autofit.js#79]
import * as echarts from "echarts/core";
 import { BarChart, LineChart } from "echarts/charts";

// 注册echarts
echarts.use([LineChart, BarChart]);
onMounted(() => {
  lineChart.value = echarts.init(document.getElementById("lineChartDom"));
  lineChart.value.setOption({
    title: {
      text: "ECharts 入门示例",
    },
    tooltip: {},
    xAxis: {
      data: ["衬衫", "羊毛衫", "雪纺衫", "裤子", "高跟鞋", "袜子"],
    },
    yAxis: {},
    series: [
      {
        name: "销量",
        type: "bar",
        data: [5, 20, 36, 10, 10, 20],
      },
    ],
  });
});

**Comment by LarryZhu-dev** [comment]
请提供复现案例：https://stackblitz.com/

**Comment by lhhboy** [comment]
> 请提供复现案例：https://stackblitz.com/

https://stackblitz.com/edit/vitejs-vite-ztnj9f87?file=src%2FApp.vue,src%2Fcomponents%2FHelloWorld.vue&terminal=dev

**Comment by LarryZhu-dev** [comment]
你提供的案例中无法正确触发 App.vue 的 onMounted 事件，请自查错误修复
