### ISSUE TITLE
当设置allowScroll为true时页面会留有左右滚动条的空白

### ISSUE THREAD

**Issue by WebRookie** [Auto-Plugin/autofit.js#81]
![image](https://github.com/user-attachments/assets/881f7ad1-bee9-4cc0-a82c-299cb8190569)
我试了一下，当设置为false的时候，就不存在了。但是这个页面还没有额外可以滚动的页面。
应该是当有额外的页面才显示滚动条吧？

**Comment by WebRookie** [comment]
![image](https://github.com/user-attachments/assets/331ca707-9947-4663-8395-3f7adb42aed6)
这样的

**Comment by LarryZhu-dev** [comment]
你好，此问题为已知问题，由于scale不会影响元素实际占位，当超出父元素时，会出现滚动条，可以尝试设置 html 超出隐藏。或者暂时禁用此参数，在元素内部另做滚动。如果还有其他问题欢迎继续留言

**Comment by WebRookie** [comment]
> 你好，此问题为已知问题，由于scale不会影响元素实际占位，当超出父元素时，会出现滚动条，可以尝试设置 html 超出隐藏。或者暂时禁用此参数，在元素内部另做滚动。如果还有其他问题欢迎继续留言

好的 thanks
