### ISSUE TITLE
Modal遮罩后页面滚动问题

### ISSUE THREAD

**Issue by VenchiBai** [Auto-Plugin/autofit.js#82]
aotufit.js会在body和app元素中都注入overflow:hidden样式，为使页面滚动我设置了#app { overflow: auto !important; }，由此引发的问题是使用遮罩后，页面仍可滚动，没办法动态切换overflow的值了。请问怎么解决？autofit能否不自动注入hidden？

**Comment by LarryZhu-dev** [comment]
可使用 allowScroll: true 参数，参考文档 https://auto-plugin.github.io/index/autofit.js/api.html
